#ifndef KAPHEIN_COMPCONST_H
#define KAPHEIN_COMPCONST_H

#define KAPHEIN_PLATFORM_UNKNOWN 0
#define KAPHEIN_PLATFORM_MSDOS 1
#define KAPHEIN_PLATFORM_WINDOWS 2
#define KAPHEIN_PLATFORM_UNIX 4
#define KAPHEIN_PLATFORM_LINUX 16
#define KAPHEIN_PLATFORM_ANDROID 17

#define KAPHEIN_ACHITECTURE_UNKNOWN 0
#define KAPHEIN_ACHITECTURE_X86 2
#define KAPHEIN_ACHITECTURE_X64 3

#define KAPHEIN_THREAD_MODEL_UNKNOWN 0
#define KAPHEIN_THREAD_MODEL_PTHREAD 1
#define KAPHEIN_THREAD_MODEL_WINTHREAD 2

#endif
