#ifndef KAPHEIN_CONFIG_H
#define KAPHEIN_CONFIG_H

#include "compconst.h"

/* ******************************** */
/* Platform */

/*
#define KAPHEIN_COMPOPT_PLATFORM_MODE 0
#define KAPHEIN_COMPOPT_PLATFORM KAPHEIN_PLATFORM_WINDOWS
*/

/* ******************************** */

/* ******************************** */
/* Architecture */

/*
#define KAPHEIN_COMPOPT_ACHITECTURE_MODE 0
#define KAPHEIN_COMPOPT_ACHITECTURE KAPHEIN_ACHITECTURE_X64
*/

/* ******************************** */

/* ******************************** */
/* Bool type */

/*
#define KAPHEIN_COMPOPT_BOOL_TYPE_MODE 0
#define KAPHEIN_COMPOPT_BOOL_TYPE unsigned char
#define KAPHEIN_COMPOPT_FALSE_VALUE 0
#define KAPHEIN_COMPOPT_TRUE_VALUE 1
*/

/* ******************************** */

/* ******************************** */
/* Integral types */

/*
#define KAPHEIN_COMPOPT_INTEGRAL_TYPE_MODE 0
#define KAPHEIN_COMPOPT_INTLEAST8_TYPE signed char
#define KAPHEIN_COMPOPT_INTLEAST8_MINIMUM 0x80
#define KAPHEIN_COMPOPT_INTLEAST8_MAXIMUM 0x7F
#define KAPHEIN_COMPOPT_UINTLEAST8_TYPE unsigned char
#define KAPHEIN_COMPOPT_UINTLEAST8_MINIMUM 0x00
#define KAPHEIN_COMPOPT_UINTLEAST8_MAXIMUM 0xFF
#define KAPHEIN_COMPOPT_INTLEAST16_TYPE signed short
#define KAPHEIN_COMPOPT_INTLEAST16_MINIMUM 0x8000
#define KAPHEIN_COMPOPT_INTLEAST16_MAXIMUM 0x7F00
#define KAPHEIN_COMPOPT_UINTLEAST16_TYPE unsigned short
#define KAPHEIN_COMPOPT_UINTLEAST16_MINIMUM 0x0000
#define KAPHEIN_COMPOPT_UINTLEAST16_MAXIMUM 0xFFFF
#define KAPHEIN_COMPOPT_INTLEAST32_TYPE signed long
#define KAPHEIN_COMPOPT_INTLEAST32_MINIMUM 0x80000000
#define KAPHEIN_COMPOPT_INTLEAST32_MAXIMUM 0x7FFFFFFF
#define KAPHEIN_COMPOPT_UINTLEAST32_TYPE unsigned long
#define KAPHEIN_COMPOPT_UINTLEAST32_MINIMUM 0x00000000
#define KAPHEIN_COMPOPT_UINTLEAST32_MAXIMUM 0xFFFFFFFF
#define KAPHEIN_COMPOPT_INTLEAST64_TYPE signed long long
#define KAPHEIN_COMPOPT_INTLEAST64_MINIMUM 0x8000000000000000
#define KAPHEIN_COMPOPT_INTLEAST64_MAXIMUM 0x7FFFFFFFFFFFFFFF
#define KAPHEIN_COMPOPT_UINTLEAST64_TYPE unsigned long long
#define KAPHEIN_COMPOPT_UINTLEAST64_MINIMUM 0x0000000000000000
#define KAPHEIN_COMPOPT_UINTLEAST64_MAXIMUM 0xFFFFFFFFFFFFFFFF
#define KAPHEIN_COMPOPT_SIZE_TYPE unsigned long long
#define KAPHEIN_COMPOPT_SIZE_MINIMUM 0x0000000000000000
#define KAPHEIN_COMPOPT_SIZE_MAXIMUM 0xFFFFFFFFFFFFFFFF
#define KAPHEIN_COMPOPT_INTPTR_TYPE long long
#define KAPHEIN_COMPOPT_INTPTR_MINIMUM 0x8000000000000000
#define KAPHEIN_COMPOPT_INTPTR_MAXIMUM 0x7FFFFFFFFFFFFFFF
#define KAPHEIN_COMPOPT_UINTPTR_TYPE unsigned long long
#define KAPHEIN_COMPOPT_UINTPTR_MINIMUM 0x0000000000000000
#define KAPHEIN_COMPOPT_UINTPTR_MAXIMUM 0xFFFFFFFFFFFFFFFF
#define KAPHEIN_COMPOPT_PTRDIFF_TYPE long long
#define KAPHEIN_COMPOPT_PTRDIFF_MINIMUM 0x8000000000000000
#define KAPHEIN_COMPOPT_PTRDIFF_MAXIMUM 0x7FFFFFFFFFFFFFFF
*/

/* ******************************** */

/* ******************************** */
/* Advanced options */

/*
#define KAPHEIN_x_PORTABLE_C_STRING_FUNCTIONS
*/

/*
#define KAPHEIN_x_EMPTY_C_MALLOC_AND_FREE
#define KAPHEIN_x_EMPTY_C_MATH
*/

/*
#undef KAPHEIN_COMPOPT_NULL_VALUE_MODE
#define KAPHEIN_COMPOPT_NULL_VALUE_MODE 0
#undef KAPHEIN_COMPOPT_NULL_VALUE
#define KAPHEIN_COMPOPT_NULL_VALUE ((void *)0)

#undef KAPHEIN_COMPOPT_BOOL_TYPE_MODE
#define KAPHEIN_COMPOPT_BOOL_TYPE_MODE 0
#undef KAPHEIN_COMPOPT_BOOL_TYPE
#define KAPHEIN_COMPOPT_BOOL_TYPE unsigned char
#undef KAPHEIN_COMPOPT_FALSE_VALUE
#define KAPHEIN_COMPOPT_FALSE_VALUE 0
#undef KAPHEIN_COMPOPT_TRUE_VALUE
#define KAPHEIN_COMPOPT_TRUE_VALUE 1

#undef KAPHEIN_COMPOPT_INT_TYPE_MODE
#define KAPHEIN_COMPOPT_INT_TYPE_MODE 0
#undef KAPHEIN_INT8_T_TYPE
#define KAPHEIN_INT8_T_TYPE signed char
#undef KAPHEIN_UINT8_T_TYPE
#define KAPHEIN_UINT8_T_TYPE unsigned char
#undef KAPHEIN_INT16_T_TYPE
#define KAPHEIN_INT16_T_TYPE signed short
#undef KAPHEIN_UINT16_T_TYPE
#define KAPHEIN_UINT16_T_TYPE unsigned short
#undef KAPHEIN_INT32_T_TYPE
#define KAPHEIN_INT32_T_TYPE signed long
#undef KAPHEIN_UINT32_T_TYPE
#define KAPHEIN_UINT32_T_TYPE unsigned long
#undef KAPHEIN_INT64_T_TYPE
#define KAPHEIN_INT64_T_TYPE signed long long
#undef KAPHEIN_UINT64_T_TYPE
#define KAPHEIN_UINT64_T_TYPE unsigned long long
#undef KAPHEIN_INTPTR_T_TYPE
#define KAPHEIN_INTPTR_T_TYPE long long
#undef KAPHEIN_UINTPTR_T_TYPE
#define KAPHEIN_UINTPTR_T_TYPE unsigned long long
#undef KAPHEIN_PTRDIFF_T_TYPE
#define KAPHEIN_PTRDIFF_T_TYPE long long
#undef KAPHEIN_SIZE_T_TYPE
#define KAPHEIN_SIZE_T_TYPE unsigned long long
*/

/* ******************************** */

/* ******************************** */
/* Library linking options */

/*
#undef KAPHEIN_COMPOPT_DLL_API_MODE
#define KAPHEIN_COMPOPT_DLL_API_MODE 1
*/

/* ******************************** */

/* ******************************** */
/* Thread options */

/*
#undef KAPHEIN_COMPOPT_THREAD_MODEL_MODE
#define KAPHEIN_COMPOPT_THREAD_MODEL_MODE 0
#undef KAPHEIN_COMPOPT_THREAD_MODEL_VALUE
#define KAPHEIN_COMPOPT_THREAD_MODEL_VALUE KAPHEIN_THREAD_MODEL_PTHREAD
*/

/* ******************************** */

#endif
